services:
  frontend:
    build: "./frontend"
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - 3000:3000
    volumes:
      - './frontend:/app'

  backend:
    build: "./backend"
    ports:
      - 3333:3333
    volumes:
      - './backend:/app'
      - '/app/node_modules'
